// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface BaiduDeviceRes {
    "device_code": string;
    "user_code": string;
    "verification_url": string;
    "qrcode_url": string;
    "expires_in": number;
    "interval": number;
}

export interface BaiduTokenRes {
    "access_token": string;
    "expires_in": number;
    "refresh_token": string;
    "expires_time": string;
    "scope": string;
}
