// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as request$0 from "../request/models.js";

export function AutoStartStatus(): $CancellablePromise<application$0.AutostartStatus> {
    return $Call.ByID(160064592);
}

export function ClearStore(): $CancellablePromise<void> {
    return $Call.ByID(171905787);
}

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(3444250859);
}

export function DisableOnWindow(): $CancellablePromise<void> {
    return $Call.ByID(4180048058);
}

export function GetDarkMode(): $CancellablePromise<boolean> {
    return $Call.ByID(968943232);
}

/**
 * store
 */
export function GetStore(key: string): $CancellablePromise<string> {
    return $Call.ByID(1134956760, key);
}

export function HasHEVCExtension(): $CancellablePromise<boolean> {
    return $Call.ByID(1839878488);
}

export function RemoveStore(key: string): $CancellablePromise<void> {
    return $Call.ByID(947968190, key);
}

export function Request(config: request$0.HttpRequestConfig): $CancellablePromise<any> {
    return $Call.ByID(2385389786, config);
}

export function SetStore(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(3973503364, key, value);
}

export function StartOnWindow(): $CancellablePromise<void> {
    return $Call.ByID(852556686);
}
