// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../utils/types/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../vo/models.js";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(680995866);
}

export function GetAuth(typee: string): $CancellablePromise<vo$0.AuthVo | null> {
    return $Call.ByID(2489757808, typee);
}

export function GetAuthList(): $CancellablePromise<vo$0.AuthVo[] | null> {
    return $Call.ByID(2223579352);
}

export function GetBaiduToken(code: string): $CancellablePromise<types$0.BaiduTokenRes | null> {
    return $Call.ByID(1332747998, code);
}

export function RefreshBaiduToken(typee: string, refreshToken: string): $CancellablePromise<types$0.BaiduTokenRes | null> {
    return $Call.ByID(1565687849, typee, refreshToken);
}

export function StartBaiduAuth(): $CancellablePromise<types$0.BaiduDeviceRes | null> {
    return $Call.ByID(43454943);
}

export function UnBindBaidu(typee: string): $CancellablePromise<void> {
    return $Call.ByID(3685789757, typee);
}
