// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../vo/models.js";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(2453291690);
}

export function GetGameList(): $CancellablePromise<vo$0.GameVo[] | null> {
    return $Call.ByID(3015457136);
}

export function UpdateGame(game: vo$0.UpdateGameVo): $CancellablePromise<void> {
    return $Call.ByID(4107184269, game);
}
