// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as live$0 from "../parse/live/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../vo/models.js";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(1989554618);
}

export function CreateLive(live: vo$0.CreateLiveVo): $CancellablePromise<void> {
    return $Call.ByID(2366990768, live);
}

export function DeleteLive(ids: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(226246763, ids);
}

export function GetLiveInfo(roomId: string, roomtype: string): $CancellablePromise<vo$0.LiveVo | null> {
    return $Call.ByID(1194518556, roomId, roomtype);
}

export function GetLiveList(): $CancellablePromise<vo$0.LiveVo[] | null> {
    return $Call.ByID(1074994888);
}

export function GetLiveRemoteInfo(roomId: string, roomtype: string): $CancellablePromise<live$0.RoomInfo | null> {
    return $Call.ByID(3618211462, roomId, roomtype);
}

export function GetPlayInfo(roomId: string, roomtype: string, extra: { [_ in string]?: string } | null): $CancellablePromise<live$0.LiveInfo | null> {
    return $Call.ByID(273281112, roomId, roomtype, extra);
}

export function OpenWeb(roomId: string, typee: string): $CancellablePromise<void> {
    return $Call.ByID(2210225512, roomId, typee);
}

export function Search(params: vo$0.LiveSearchVo): $CancellablePromise<live$0.LiveResponse<live$0.RoomInfo> | null> {
    return $Call.ByID(997476670, params);
}

export function UpdateLive(live: vo$0.UpdateLiveVo): $CancellablePromise<void> {
    return $Call.ByID(1542198941, live);
}

export function UpdateTtwid(ttwid: string): $CancellablePromise<void> {
    return $Call.ByID(1039365085, ttwid);
}
