// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as video$0 from "../parse/video/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../vo/models.js";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(4281020861);
}

export function CreateParsers(source: string): $CancellablePromise<vo$0.Result<video$0.ParseOption>> {
    return $Call.ByID(2828073897, source);
}

export function DeleteParser(ids: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(1033760211, ids);
}

export function GetParserList(): $CancellablePromise<vo$0.ParserVo[] | null> {
    return $Call.ByID(331845034);
}

export function UpdateToken(id: number, token: string): $CancellablePromise<void> {
    return $Call.ByID(2933648899, id, token);
}
