// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vo$0 from "../vo/models.js";

export function Close(): $CancellablePromise<void> {
    return $Call.ByID(3304390458);
}

/**
 * setting
 */
export function GetConfig(): $CancellablePromise<vo$0.SettingVo> {
    return $Call.ByID(2448142292);
}

/**
 * menu
 */
export function GetMenuList(): $CancellablePromise<vo$0.MenuVo[] | null> {
    return $Call.ByID(3235152377);
}

export function UpdateConfig(config: vo$0.UpdateSettingVo): $CancellablePromise<void> {
    return $Call.ByID(296716661, config);
}

export function UpdateMenu(menu: vo$0.UpdateMenuVo): $CancellablePromise<void> {
    return $Call.ByID(2981887912, menu);
}
