// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../utils/types/models.js";

export function Close(name: string): $CancellablePromise<void> {
    return $Call.ByID(1802588904, name);
}

export function CloseAll(): $CancellablePromise<void> {
    return $Call.ByID(3048839403);
}

export function GetAllWindows(): $CancellablePromise<string[] | null> {
    return $Call.ByID(343403320);
}

export function OpenNewWindow(options: types$0.WindowOptions): $CancellablePromise<void> {
    return $Call.ByID(4250033726, options);
}
