// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface CdnsWithName {
    "name": string;
    "cdn": string;

    /**
     * huya,douyin
     */
    "streamName": string;
}

export interface LiveInfo {
    "roomId": string;
    "url": string;
    "videoType": string;
    "rtmpCdn": string;
    "rate": string;
    "multirates": Multirate[] | null;
    "cdnsWithName": CdnsWithName[] | null;
}

export interface LiveResponse<T> {
    "data": T[] | null;
    "total": number;
}

export interface Multirate {
    "name": string;
    "rate": string;
}

export interface RoomInfo {
    "roomId": string;
    "type": string;
    "roomName": string;
    "ownerName": string;
    "ownerAvatar": string;
    "isLive": boolean;
    "isReplay": boolean;
    "roomPic": string;
    "description": string;
}
