// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../utils/types/models.js";

export interface AuthVo {
    "name": string;
    "type": string;
    "icon": string;
    "token": string;
    "expires_in": number;
    "expires_time": string;
    "refresh_token": string;
    "scope": string;
    "id": number;
    "avatar": string;
    "username": string;
    "nickname": string;
    "vip_type": number;
    "createdAt": types$0.Datetime;
    "updatedAt": types$0.Datetime;
}

export interface CreateLiveVo {
    "roomId": string;
    "type": string;
}

export interface GameVo {
    "name": string;
    "type": string;
    "command": string;
    "customCommand": string;
    "installFolder": string;
    "modsFolder": string;
    "saveFolder": string;
    "size": number;
    "modsSize": number;
    "isSupportOpenWindow": number;
    "path": string;
    "isFixed": number;
    "hidden": number;
    "id": number;
    "createdAt": types$0.Datetime;
    "updatedAt": types$0.Datetime;
}

export interface LiveSearchVo {
    "page": string;
    "keyword": string;
    "type": string;
}

export interface LiveVo {
    "roomName": string;
    "ownerName": string;
    "ownerAvatar": string;
    "isLive": boolean;
    "isReplay": boolean;
    "roomPic": string;
    "description": string;
    "roomId": string;
    "rid": string;
    "type": string;
    "sort": number | null;
    "isSpecial": number;
    "id": number;
    "createdAt": types$0.Datetime;
    "updatedAt": types$0.Datetime;
}

export interface MenuVo {
    "name": string;
    "nickName": string;
    "icon": string;
    "path": string;
    "size": number;
    "hidden": number;
    "id": number;
    "createdAt": types$0.Datetime;
    "updatedAt": types$0.Datetime;
}

export interface ParserVo {
    "type": string;
    "source": string;
    "version": string;
    "author": string;
    "description": string;
    "icon": string;
    "subType": string;
    "homePage": string;
    "token": string;
    "id": number;
    "createdAt": types$0.Datetime;
    "updatedAt": types$0.Datetime;
}

export interface Result<T> {
    "message": string;
    "data": T[] | null;
}

export interface SettingVo {
    "closeBehavior": number;
    "theme": number;
    "colorTheme": string;
    "lang": string;
    "videoDetailTabActive": string;
    "videoDetailGrid": string;
    "videoDetailSort": string;
    "videoSourceType": string;
    "animeSourceType": string;
    "liveShowType": string;
    "liveSpecialShowType": string;
    "animeWeeklyType": string;
    "id": number;
    "createdAt": types$0.Datetime;
    "updatedAt": types$0.Datetime;
}

export interface UpdateGameVo {
    "customCommand": string;
    "installFolder": string;
    "modsFolder": string;
    "saveFolder": string;
    "path": string;
    "isFixed": number;
    "hidden": number;
    "id": number;
}

export interface UpdateLiveVo {
    "sort": number | null;
    "isSpecial": number;
    "id": number;
}

export interface UpdateMenuVo {
    "name": string;
    "nickName": string;
    "icon": string;
    "path": string;
    "size": number;
    "hidden": number;
    "id": number;
}

export interface UpdateSettingVo {
    "closeBehavior": number;
    "theme": number;
    "colorTheme": string;
    "lang": string;
    "videoDetailTabActive": string;
    "videoDetailGrid": string;
    "videoDetailSort": string;
    "videoSourceType": string;
    "animeSourceType": string;
    "liveShowType": string;
    "liveSpecialShowType": string;
    "animeWeeklyType": string;
    "id": number;
}
