// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as types$0 from "../../../../../pql/pkg/utils/types/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "app:set:change": string;
            "app:theme": types$0.WindowTheme;
            "page:change": types$0.PageChange;
            "window:maximise": types$0.WindowState;
            "window:restore": types$0.WindowState;
            "window:unMaximise": types$0.WindowState;
        }
    }
}
