// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type Datetime = any;

export interface PageChange {
    "type": string;
    "path": string;
}

export interface WindowOptions {
    "name": string;
    "path": string;
    "title": string;
}

export interface WindowState {
    "type": string;
    "name": string;
}

export interface WindowTheme {
    "type": string;
    "theme": number;
}
