// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface LabelValue {
    "type"?: string;
    "extra"?: any[] | null;
    "label"?: string;
    "path"?: string;
    "copy"?: boolean;
    "template"?: string;
    "separator"?: string;
}

export interface ParseOption {
    "type"?: string;
    "author"?: string;
    "version"?: string;
    "email"?: string;
    "description"?: string;
    "defaultSize"?: number | null;
    "defaultMaxSize"?: number | null;
    "icon"?: string;
    "homePage"?: string;
    "subType"?: string;
    "headers"?: { [_ in string]?: string } | null;
    "domain"?: string;
    "imgdomain"?: string;
    "authorization"?: string;
    "response"?: Response | null;
    "loginApi"?: RuleItem | null;
    "typeApi"?: RuleItem | null;
    "dataApi"?: RuleItem | null;
    "searchTypeApi"?: RuleItem | null;
    "searchApi"?: RuleItem | null;
    "detailApi"?: RuleItem | null;
    "sourceApi"?: RuleItem | null;
    "episodeApi"?: RuleItem | null;
    "playUrlApi"?: RuleItem | null;
    "scheduleApi"?: RuleItem | null;
}

export interface Response {
    "codeok"?: number | null;
    "codeExpired"?: number | null;
    "codePath"?: string;
    "dataPath"?: string;
    "messagePath"?: string;
}

export interface RuleItem {
    "url"?: string;
    "method"?: string;
    "options"?: any[] | null;
    "isAuth"?: boolean;
    "dataPath"?: string;
    "parseType"?: string;
    "primaryPath"?: string;
    "namePath"?: string;
    "childrenPath"?: string;
    "childParseType"?: string;
    "childPrimaryPath"?: string;
    "childNamePath"?: string;
    "coverTopPath"?: string;
    "coverLeftPath"?: string;
    "coverRightPath"?: string;
    "srcPath"?: string;
    "next"?: { [_ in string]?: any } | null;
    "data"?: { [_ in string]?: any } | null;
    "paging"?: boolean;
    "totalPath"?: string;
    "requestCount"?: number | null;
    "titlePath"?: string;
    "detailList"?: LabelValue[] | null;
    "descriptionList"?: LabelValue[] | null;
    "omitempty"?: boolean;
}
