// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type H = { [_ in string]?: any } | null;

export interface HttpRequestConfig {
    "url": string;
    "method": string;
    "params": H;
    "data": H;
    "headers": H;
}
