// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AutostartStatus describes the current autostart registration.
 */
export interface AutostartStatus {
    /**
     * Enabled reports whether a registration exists.
     */
    "Enabled": boolean;

    /**
     * Path is the on-disk location of the registration artefact, when
     * applicable (plist path, .desktop path, registry sub-key path). Empty if
     * Enabled is false.
     */
    "Path": string;

    /**
     * Strategy names the mechanism that registered the application. Empty if
     * Enabled is false or the platform has only one mechanism.
     */
    "Strategy": AutostartStrategy;
}

/**
 * AutostartStrategy names the underlying mechanism a registration used.
 * 
 * On macOS this distinguishes between SMAppService (bundled .app on macOS 13+)
 * and a LaunchAgent plist (the fallback path). On Windows it is always
 * AutostartStrategyRegistryRun and on Linux always AutostartStrategyXDGAutostart.
 * Empty when AutostartStatus.Enabled is false.
 */
export enum AutostartStrategy {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    AutostartStrategyNone = "",
    AutostartStrategySMAppService = "smappservice",
    AutostartStrategyLaunchAgent = "launchagent",
    AutostartStrategyRegistryRun = "registry-run",
    AutostartStrategyXDGAutostart = "xdg-autostart",
};
